# Generated by Django 2.2.3 on 2019-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField(max_length=2000)),
                ('pic', models.CharField(max_length=255)),
                ('tanggal_pembuatan', models.DateField(auto_now=True)),
                ('comment', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
