# Generated by Django 2.2.3 on 2019-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('quotes', models.TextField(max_length=255)),
                ('pic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Experience (in years)')),
                ('quotes', models.TextField(max_length=255)),
                ('pic', models.CharField(max_length=255)),
            ],
        ),
    ]
