# Generated by Django 2.2.3 on 2019-07-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mentee_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.CharField(max_length=255),
        ),
    ]
