# Generated by Django 2.2.3 on 2019-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190723_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='julukan',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Experience (in years)'),
        ),
    ]
